### ISSUE TITLE
Error en la consulta del estado de la documentación del trabajador 45980901Z

### ISSUE THREAD

**Issue by igalarraga** [Dokify/api#1]
Buenos días,

Estamos viendo que la llamada al servicio https://dokify.net/app/employee/45980901Z/docs?only-mandatory=1&only-pending=1 no nos devuelve el JSON como respuesta.

¿podéis revisarlo? Adjunto cURL.
[cURL doc.txt](https://github.com/Dokify/api/files/13376932/cURL.doc.txt)

Gracias.

**Comment by LdonosoC** [comment]
Según veo en la url, quereis hacer la petición a producción no? Pues es que para hacer las peticiones a producción hay que hacerlas a `app.dokify.net` y la estáis haciendo a `dokify.net`
